defaults: &defaults
  adapter: postgresql
  username: <%= ENV['USER'] %>

development:
  <<: *defaults
  database: unicef_tinyboxes_development

test: &test
  <<: *defaults
  database: unicef_tinyboxes_test

production:
  <<: *defaults

cucumber:
  <<: *test